export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
  },
  users: {
    me: '/users/me',
    preferences: '/users/me/preferences',
  },
  tasks: {
    list: '/tasks',
    detail: (id: string) => '/tasks/' + id,
    steps: (id: string) => '/tasks/' + id + '/steps',
    focusSessions: (id: string) => '/tasks/' + id + '/focus-sessions',
    simplify: (id: string) => '/tasks/' + id + '/simplify',
    complete: (id: string) => '/tasks/' + id + '/complete',
    byDate: (date: string) => '/tasks/date/' + date,
  },
  focus: {
    start: '/focus/start',
    pause: (id: string) => '/focus/' + id + '/pause',
    resume: (id: string) => '/focus/' + id + '/resume',
    complete: (id: string) => '/focus/' + id + '/complete',
    cancel: (id: string) => '/focus/' + id + '/cancel',
    active: '/focus/active',
    list: '/focus',
    detail: (id: string) => '/focus/' + id,
  },
  goals: {
    list: '/goals',
    detail: (id: string) => '/goals/' + id,
    archive: (id: string) => '/goals/' + id + '/archive',
    feasibility: (id: string) => '/goals/' + id + '/feasibility',
    projection: (id: string) => '/goals/' + id + '/projection',
    milestones: (id: string) => '/goals/' + id + '/milestones',
    milestoneDetail: (goalId: string, milestoneId: string) => '/goals/' + goalId + '/milestones/' + milestoneId,
    plans: (id: string) => '/goals/' + id + '/plans',
    planDetail: (goalId: string, planId: string) => '/goals/' + goalId + '/plans/' + planId,
  },
  goalHealth: {
    detail: (goalId: string) => '/goal-health/' + goalId,
    recalculate: (goalId: string) => '/goal-health/' + goalId + '/recalculate',
  },
  insights: {
    list: '/insights',
    detail: (id: string) => '/insights/' + id,
    markRead: (id: string) => '/insights/' + id + '/read',
    dismiss: (id: string) => '/insights/' + id + '/dismiss',
    markAllRead: '/insights/read-all',
    dailyBrief: '/insights/daily-brief',
    behavioralAwareness: '/insights/behavioral-awareness',
    weeklyReview: '/insights/weekly-review',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    detail: (id: string) => '/notifications/' + id,
    markRead: (id: string) => '/notifications/' + id + '/read',
    markAllRead: '/notifications/read-all',
    preferences: '/notifications/preferences',
  },
  behavior: {
    track: '/behavior',
    list: '/behavior',
    stats: '/behavior/stats',
    detail: (id: string) => '/behavior/' + id,
    dailyMetrics: (date?: string) => '/behavior/metrics/daily' + (date ? '?date=' + date : ''),
    weeklyMetrics: (weekStart?: string) => '/behavior/metrics/weekly' + (weekStart ? '?weekStart=' + weekStart : ''),
    indicators: (days?: number) => '/behavior/metrics/indicators' + (days ? '?days=' + days : ''),
    burnout: '/behavior/metrics/burnout',
    procrastination: '/behavior/metrics/procrastination',
  },
  execution: {
    readiness: '/execution/readiness',
    resistance: '/execution/resistance',
    momentum: '/execution/momentum',
    stats: '/execution/stats',
  },
  ai: {
    recommendations: '/ai/recommendations',
    generateRecommendation: '/ai/recommendations/generate',
    acceptRecommendation: (id: string) => '/ai/recommendations/' + id + '/accept',
    dismissRecommendation: (id: string) => '/ai/recommendations/' + id + '/dismiss',
    dailyBrief: '/ai/daily-brief',
    breakdownTask: (taskId: string) => '/ai/breakdown-task/' + taskId,
    stuckAnalysis: '/ai/stuck-analysis',
    weeklyReview: '/ai/weekly-review',
    goalRecovery: (goalId: string) => '/ai/goal-recovery/' + goalId,
    usage: '/ai/usage',
    usageSummary: '/ai/usage/summary',
    usageByFeature: '/ai/usage/by-feature',
    usageByDay: '/ai/usage/by-day',
    metrics: '/ai/metrics',
    status: '/ai/status',
  },
};
